/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_biblioteca;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    Usuarios[] usuario;
    Libros[] libros;

    public Admin(Usuarios[] usuario, Libros[] libros) {
        initComponents();
        this.usuario = usuario;
        this.libros = libros;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Usuarios");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modificar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Bibliografías");

        jButton12.setText("Carga indivual");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("Carga masiva");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton6.setText("Modificar");

        jButton7.setText("Eliminar");

        jButton8.setText("Mostrar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Reportes");

        jButton10.setText("Reporte libros");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton9.setText("Reporte Usuarios");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton11.setText("Cerrar sesión");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton13)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton6)))
                            .addGap(18, 18, 18)
                            .addComponent(jButton7)
                            .addGap(18, 18, 18)
                            .addComponent(jButton8))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton1)
                                .addComponent(jLabel1))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton2)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jButton4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton11))))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton9))
                .addGap(0, 30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Crear_usuario crear = new Crear_usuario(this, true, usuario);
        crear.setVisible(true);
        usuario = crear.getGuardar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Mostrar_usuario ver = new Mostrar_usuario(this, true, usuario);
        ver.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Modificar_usuario modificar = new Modificar_usuario(this, true, usuario);
        modificar.setVisible(true);
        usuario = modificar.getModificar();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Eliminar_usuario eliminar = new Eliminar_usuario(this, true, usuario);
        eliminar.setVisible(true);
        usuario = eliminar.getEliminar();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Login login = new Login(usuario, libros);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        Carga_individual indi = new Carga_individual(this, true, libros);
        indi.setVisible(true);
        libros = indi.getLibros();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Mostrar_biblio mostrar = new Mostrar_biblio(this, true, libros);
        mostrar.setVisible(true);

    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Carga_masiva masiva = new Carga_masiva(this, true, libros);
        masiva.setVisible(true);
        libros = masiva.getLibros();
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String cwd = System.getProperty("user.dir");
        File dir = new File(cwd + "\\Reportes");
        FileWriter escribir;
        PrintWriter nuevaLinea;
        if (!dir.exists() && !dir.isDirectory()) {
            try {
                dir.mkdir();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        File archivo = new File(cwd + "\\Reportes\\reportelibros.html");
        archivo.delete();
        try {
            archivo.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            escribir = new FileWriter(archivo, true);
            nuevaLinea = new PrintWriter(escribir);
            nuevaLinea.println("<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "<head>\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <title>Reporte</title>\n"
                    + "</head>\n"
                    + "<body>");

            nuevaLinea.println("<h1>Reporte libros</h1>");
            for (int i = 0; i < libros.length; i++) {
                if (libros[i] != null) {
                    //muestro el libro
                    nuevaLinea.println("<p><b>Titulo:</b> " + libros[i].getTitulo() + "</p>");
                    nuevaLinea.println("<p><b>Autor:</b> " + libros[i].getAutor() + "</p>");
                    nuevaLinea.println("<p><b>Descripcion:</b></p><p>" + libros[i].getDescripcion() + "</p>");
                    nuevaLinea.println("<table border=\"1\">");
                    nuevaLinea.println("<tr>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Nombre</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Apellido</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Rol</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.println("</tr>");
                    for (int j = 0; j < usuario.length; j++) {
                        if (usuario[j] != null) {
                            for (int k = 0; k < usuario[j].getLibros().length; k++) {
                                if (usuario[j].getLibros()[k] != null) {
                                    if (usuario[j].getLibros()[k].equals(libros[i])) {
                                        //si el libro coincide con el libro prestado por cada usuario
                                        //fila de datos del usuario
                                        nuevaLinea.println("<tr>");
                                        nuevaLinea.print("<td>");
                                        nuevaLinea.print(usuario[j].getNombre());
                                        nuevaLinea.print("</td>");
                                        nuevaLinea.print("<td>");
                                        nuevaLinea.print(usuario[j].getApellido());
                                        nuevaLinea.print("</td>");
                                        nuevaLinea.print("<td>");
                                        nuevaLinea.print(usuario[j].getRol());
                                        nuevaLinea.print("</td>");
                                        nuevaLinea.println("</tr>");
                                    }
                                }
                            }
                        }
                    }
                    nuevaLinea.println("</table>");
                    nuevaLinea.println(" ");
                    nuevaLinea.println("<p>----------------------------------------------------------------------------------------------</p>");
                }
            }
            // ---------------------------
            nuevaLinea.println("</body>\n"
                    + "</html>");
            // me cierra mi archivo
            escribir.close();
            JOptionPane.showMessageDialog(this, "El reporte se ha creado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String cwd = System.getProperty("user.dir");
        File dir = new File(cwd + "\\Reportes");
        FileWriter escribir;
        PrintWriter nuevaLinea;
        if (!dir.exists() && !dir.isDirectory()) {
            try {
                dir.mkdir();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        }
        File archivo = new File(cwd + "\\Reportes\\reporteusuarios.html");
        archivo.delete();
        try {
            archivo.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            escribir = new FileWriter(archivo, true);
            nuevaLinea = new PrintWriter(escribir);
            nuevaLinea.println("<!DOCTYPE html>\n"
                    + "<html lang=\"en\">\n"
                    + "<head>\n"
                    + "    <meta charset=\"UTF-8\">\n"
                    + "    <title>Reporte</title>\n"
                    + "</head>\n"
                    + "<body>");

            nuevaLinea.println("<h1>Reporte usuarios</h1>");
            for (int i = 1; i < usuario.length; i++) {
                if (usuario[i] != null) {
                    //muestro el libro
                    nuevaLinea.println("<p><b>Nombres:</b> " + usuario[i].getNombre() + "</p>");
                    nuevaLinea.println("<p><b>Apellidos:</b> " + usuario[i].getApellido() + "</p>");
                    nuevaLinea.println("<p><b>Rol:</b></p><p>" + usuario[i].getRol() + "</p>");
                    nuevaLinea.println("<table border=\"1\">");
                    nuevaLinea.println("<tr>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Titulo</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Autor</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Año de publicación</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.print("<td>");
                    nuevaLinea.print("<b>Tipo</b>");
                    nuevaLinea.print("</td>");
                    nuevaLinea.println("</tr>");
                    for (int j = 0; j < usuario[i].getLibros().length; j++) {
                        if (usuario[i].getLibros()[j] != null) {
                            //si el libro coincide con el libro prestado por cada usuario
                            //fila de datos del usuario
                            nuevaLinea.println("<tr>");
                            nuevaLinea.print("<td>");
                            nuevaLinea.print(usuario[i].getLibros()[j].getTitulo());
                            nuevaLinea.print("</td>");
                            nuevaLinea.print("<td>");
                            nuevaLinea.print(usuario[i].getLibros()[j].getAutor());
                            nuevaLinea.print("</td>");
                            nuevaLinea.print("<td>");
                            nuevaLinea.print(usuario[i].getLibros()[j].getAnio_publi());
                            nuevaLinea.print("</td>");
                            nuevaLinea.print("<td>");
                            nuevaLinea.print(usuario[i].getLibros()[j].getTipo());
                            nuevaLinea.print("</td>");
                            nuevaLinea.println("</tr>");

                        }
                    }
                    nuevaLinea.println("</table>");
                    nuevaLinea.println(" ");
                    nuevaLinea.println("<p>----------------------------------------------------------------------------------------------</p>");
                }
            }
            // ---------------------------
            nuevaLinea.println("</body>\n"
                    + "</html>");
            // me cierra mi archivo
            escribir.close();
            JOptionPane.showMessageDialog(this, "El reporte se ha creado con exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void regresar() {

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
