/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto1_biblioteca;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruben
 */
public class Biblio_virtual extends javax.swing.JFrame {

    /**
     * Creates new form Biblio_virtual
     */
    Usuarios[] usuarios;
    Libros[] libros;
    int posi;
    int[] prestamos;

    public Biblio_virtual(Usuarios[] usuarios, Libros[] libros, int posi, int[] prestamos) {
        this.usuarios = usuarios;
        this.libros = libros;
        this.posi = posi;
        this.prestamos = prestamos;
        initComponents();
        int j = 0;
        for (int i = 0; i < libros.length; i++) {
            if (libros[i] != null) {
                j++;
                mostrar(j, i);
            }

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_libros = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        combo_atributo = new javax.swing.JComboBox<>();
        txt_buscar = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla_libros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Autor", "Año ", "Titulo", "Edición", "Descripción", "Tamaño"
            }
        ));
        jScrollPane1.setViewportView(tabla_libros);

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ver biblioteca virtual");

        combo_atributo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Autor", "Año Publicación", "Título", "Edición", "Palabras Clave", "Descripción", "Temas", "Tamaño" }));

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cerrar sesión");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(240, 240, 240)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_buscar)
                            .addComponent(combo_atributo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combo_atributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modelo = (DefaultTableModel) tabla_libros.getModel();
        int fila = tabla_libros.getRowCount();
        for (int i = 0; i < fila; i++) {
            modelo.removeRow(0);
        }
        int j = 0;
        switch (combo_atributo.getSelectedIndex()) {
            case 0:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (libros[i].getAutor().equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 1:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (String.valueOf(libros[i].getAnio_publi()).equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 2:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (libros[i].getTitulo().equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 3:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (String.valueOf(libros[i].getEdicion()).equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 4://palabras clave, falta
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (libros[i].getAutor().equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 5:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (libros[i].getDescripcion().equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 6://temas falta
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (libros[i].getAutor().equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            case 7:
                for (int i = 0; i < libros.length; i++) {
                    if (libros[i] != null) {
                        if (String.valueOf(libros[i].getTamano()).equals(txt_buscar.getText())) {
                            mostrar(j, i);
                            j++;
                        }
                    }
                }
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Usuario_comun regresar = new Usuario_comun(usuarios, libros, posi, prestamos);
        regresar.setVisible(true);
        this.hide();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Login login = new Login(usuarios, libros, prestamos);
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    public void mostrar(int i, int j) {
        Object matriz[][] = new Object[libros.length][14];
        if (libros[j].getTipo() == 3) {
            matriz[i][0] = i;
            matriz[i][1] = libros[j].getAutor();
            matriz[i][2] = String.valueOf(libros[j].getAnio_publi());
            matriz[i][3] = libros[j].getTitulo();
            matriz[i][4] = String.valueOf(libros[j].getEdicion());
            matriz[i][5] = libros[j].getDescripcion();
            matriz[i][6] = String.valueOf(libros[j].getTamano());
            DefaultTableModel model = (DefaultTableModel) tabla_libros.getModel();
            model.addRow(matriz[i]);
        }

    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_atributo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_libros;
    private javax.swing.JTextField txt_buscar;
    // End of variables declaration//GEN-END:variables
}
