/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1_biblioteca;

/**
 *
 * @author ruben
 */
public class Mostrar_usuario extends javax.swing.JDialog {

    /**
     * Creates new form Mostrar_usuario
     */
    Usuarios[] mostrar;
    public Mostrar_usuario(java.awt.Frame parent, boolean modal,Usuarios[] usuarios) {
        super(parent, modal);
        this.mostrar=usuarios;
        
        initComponents();
        mostrar();
    }
    public void mostrar(){
        String matriz[][]= new String[mostrar.length][7];
        for (int i = 0; i < mostrar.length; i++) {
            if (mostrar[i]!=null) {
                matriz[i][0]=String.valueOf(i);
                matriz[i][1]=String.valueOf(mostrar[i].getDpi());
                matriz[i][2]=mostrar[i].getNombre();
                matriz[i][3]=mostrar[i].getApellido();
                matriz[i][4]=mostrar[i].getUser();
                matriz[i][5]=mostrar[i].getRol();
                matriz[i][6]=mostrar[i].getPass();
            }           
        }
         Table_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "No.", "DPI","Nombre", "Apellido","User","Rol","Contraseña"
            }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_mostrar = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ver Usuarios");

        Table_mostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table_mostrar);

        jLabel1.setText("LISTADO DE USUARIOS REGISTRADOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table_mostrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
