/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto1_biblioteca;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ruben
 */
public class Ver_prestamos extends javax.swing.JDialog {

    /**
     * Creates new form Ver_prestamos
     */
    Usuarios[] usuario;
    Libros[] libro;
    int posi;
    int[] disponibles;

    public Ver_prestamos(java.awt.Frame parent, boolean modal, Usuarios[] usuario, int posi,Libros[] libro) {
        super(parent, modal);
        this.usuario = usuario;
        this.libro=libro;
        this.posi = posi;
        this.disponibles = new int[50];
        initComponents();
        mostrar();
    }

    public Usuarios[] getUsuario() {
        return usuario;
    }

    public Libros[] getLibro() {
        return libro;
    }
    
    private void mostrar() {
        int j = 0;
        Object matriz[][] = new Object[usuario[posi].getLibros().length][5];
        for (int i = 0; i < usuario[posi].getLibros().length; i++) {
            if (usuario[posi].getLibros()[i] != null) {
                if (usuario[posi].getLibros()[i].getTipo() != 3) {
                    disponibles[j] = i;
                    matriz[j][0] = j;
                    matriz[j][1] = usuario[posi].getLibros()[i].getTitulo();
                    switch (usuario[posi].getLibros()[i].getTipo()) {
                        case 0:
                            matriz[j][2] = "Libro";
                            break;
                        case 1:
                            matriz[j][2] = "Revista";
                            break;
                        case 2:
                            matriz[j][2] = "Tesis";
                            break;
                        default:
                            throw new AssertionError();
                    }
                    DefaultTableModel model = (DefaultTableModel) tabla_pres.getModel();
                    model.addRow(matriz[j]);
                    j++;
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_pres = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabla_pres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Título", "Tipo"
            }
        ));
        jScrollPane1.setViewportView(tabla_pres);

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Listado de prestamos");

        jButton3.setText("Devolver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(201, 201, 201))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2)
                        .addComponent(jButton3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton2)
                .addGap(2, 2, 2)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (tabla_pres.getSelectedRow() != -1) {
            int i = disponibles[tabla_pres.getSelectedRow()];
            
            for (int j = 0; j < libro.length; j++) {
                if (usuario[posi].getLibros()[i].equals(libro[j])) {
                    libro[j].setDisponible(libro[j].getDisponible() + 1);
                }
            }
            for (; i < usuario[posi].getLibros().length - 1; i++) {
                usuario[posi].getLibros()[i] = usuario[posi].getLibros()[i + 1];
            }
            DefaultTableModel model = (DefaultTableModel) tabla_pres.getModel();
            int fila = tabla_pres.getRowCount();
            for (int k = 0; k < fila; k++) {
                model.removeRow(0);
            }
            JOptionPane.showMessageDialog(this, "Se ha devuelto el libro a la biblioteca");
            mostrar();
        }else{
             JOptionPane.showMessageDialog(null, "Seleccione una fila", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_pres;
    // End of variables declaration//GEN-END:variables
}
